"""Every quantitative claim on the front page must have a source.

This project has shipped a false number twice: "the winner separates cleanly"
(it did not) and "three different strategies win depending on the document"
(there were two). Both were written from memory, both were caught by hand, and
nothing stopped either from being written in the first place.

The README and the docs index are the surface a stranger reads before deciding
whether to trust the tool, so every result number there is listed in CLAIMS with
the command that reproduces it. Adding a number without adding its source fails
this test; changing a number without re-measuring fails it too.

Deeper pages carry measured tables that are too numerous to enumerate, so the
rule there is weaker but still real: a page reporting results must say how to
reproduce them.
"""

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
README = ROOT / "README.md"
INDEX = ROOT / "docs" / "index.md"

#: value -> where it comes from. The value is matched literally against the prose.
CLAIMS: dict[str, str] = {
    # README, "60-second quickstart" commentary. Reproduce with:
    #   chunklab run --docs examples/corpus --questions examples/questions.yaml
    # and a paired bootstrap between the named strategies.
    "+0.111": "recursive - semantic_no_floor recall difference, example corpus",
    "+0.099": "structure - semantic_no_floor recall difference, example corpus",
    "+0.103": "fixed - semantic_no_floor recall difference, example corpus",
    "2,128": "structure retrieved_tokens_at_k, example corpus",
    "2,447": "fixed retrieved_tokens_at_k, example corpus",
    # README + index, opening. Reproduce with scripts/benchmarks/ (docs/benchmarks.md).
    "+0.000": "structure - recursive recall difference, QASPER 889 questions",
    "+0.034": "recursive - structure recall difference, QASPER 70 questions",
    "35%": "structure vs recursive retrieved-token saving, QASPER 889 questions",
    # Standard confidence level, not a measurement.
    "95%": "the confidence level used throughout",
}

#: Pages reporting measured results must carry a "Reproducing" section.
RESULT_PAGES = ("benchmarks.md", "metrics.md")

#: Decimals, percentages, and magnitudes written with thousands separators —
#: the three shapes a measured result takes. Bare small integers ("5 documents",
#: "top_k=5") are structure, not evidence, and stay out.
#: Percentages first: alternation is leftmost-first, so putting decimals first
#: would report "99.9%" as the bare "99.9" and make the failure harder to read.
_NUMBER = re.compile(
    r"(?<![\w.])[+-]?\d+(?:,\d{3})*(?:\.\d+)?\s*%"
    r"|(?<![\w.])[+-]?\d+(?:,\d{3})*\.\d+(?![\w.])"
    r"|(?<![\w.])\d{1,3}(?:,\d{3})+(?![\w.])"
)


def prose(text: str) -> str:
    """Markdown minus what the author did not assert.

    Fenced blocks are generated output, regenerated by
    scripts/regen_readme_example.py and checked for drift in CI; link targets are
    not prose. Inline code is **not** stripped: `+0.000` in backticks is exactly
    as much of a claim as +0.000 without them, and exempting it would leave the
    easiest way to smuggle an unsourced number past this test.
    """
    text = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    text = re.sub(r"https?://\S+", "", text)
    text = re.sub(r"\]\([^)]*\)", "]", text)
    return text


def numbers_in(path: Path) -> set[str]:
    return {match.strip() for match in _NUMBER.findall(prose(path.read_text(encoding="utf-8")))}


@pytest.mark.parametrize("page", [README, INDEX], ids=lambda p: p.name)
def test_every_front_page_number_has_a_source(page):
    unsourced = numbers_in(page) - set(CLAIMS)
    assert not unsourced, (
        f"{page.name} states {sorted(unsourced)} with no entry in CLAIMS. "
        "Add the number with the command that reproduces it, or remove it."
    )


def test_claims_list_has_no_dead_entries():
    """A claim nobody makes any more is a claim nobody re-measures."""
    stated = numbers_in(README) | numbers_in(INDEX)
    dead = set(CLAIMS) - stated
    assert not dead, f"CLAIMS lists {sorted(dead)}, which no longer appear on the front pages"


@pytest.mark.parametrize("page", RESULT_PAGES)
def test_result_pages_say_how_to_reproduce_them(page):
    text = (ROOT / "docs" / page).read_text(encoding="utf-8")
    assert "Reproduc" in text, f"docs/{page} reports measured results without a Reproducing section"
    assert "```" in text, f"docs/{page} has no command block to reproduce its numbers"


def test_no_unsourced_retrieval_failure_stat():
    """The old "failure is in retrieval roughly 70% of the time" claim."""
    assert not re.search(r"70\s*%", prose(README.read_text(encoding="utf-8")))


def test_no_unsourced_chunking_swing_stat():
    """The old "~15-percentage-point swing" claim."""
    assert not re.search(
        r"15[\s-]*percentage", prose(README.read_text(encoding="utf-8")), flags=re.IGNORECASE
    )
